// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1qTtDdgzkeBStgxWdnmOOGmXc6dfjLyE',
    appId: '1:895905616219:web:29a60035c1a2abe995ca7e',
    messagingSenderId: '895905616219',
    projectId: 'examenflutter2ev',
    authDomain: 'examenflutter2ev.firebaseapp.com',
    storageBucket: 'examenflutter2ev.firebasestorage.app',
    measurementId: 'G-X5TQL8VJ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPiNmMylXSHHscfV2qsljrLlEsFYkPnNM',
    appId: '1:895905616219:android:0ff4b6863336fdda95ca7e',
    messagingSenderId: '895905616219',
    projectId: 'examenflutter2ev',
    storageBucket: 'examenflutter2ev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXyrxskwqBJA-lKKHL3UZhDn1Ap8UKV2I',
    appId: '1:895905616219:ios:57e600977f1cc71195ca7e',
    messagingSenderId: '895905616219',
    projectId: 'examenflutter2ev',
    storageBucket: 'examenflutter2ev.firebasestorage.app',
    iosBundleId: 'com.example.examen2ev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXyrxskwqBJA-lKKHL3UZhDn1Ap8UKV2I',
    appId: '1:895905616219:ios:57e600977f1cc71195ca7e',
    messagingSenderId: '895905616219',
    projectId: 'examenflutter2ev',
    storageBucket: 'examenflutter2ev.firebasestorage.app',
    iosBundleId: 'com.example.examen2ev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1qTtDdgzkeBStgxWdnmOOGmXc6dfjLyE',
    appId: '1:895905616219:web:363af0508d1c005495ca7e',
    messagingSenderId: '895905616219',
    projectId: 'examenflutter2ev',
    authDomain: 'examenflutter2ev.firebaseapp.com',
    storageBucket: 'examenflutter2ev.firebasestorage.app',
    measurementId: 'G-J4QPL2871R',
  );
  
}
